### ISSUE TITLE
SSL verify failed: Version Python 3.8.5 [GCC 7.3.0] :: Anaconda. on linux

### ISSUE THREAD

**Issue by russelljjarvis** [neuromorphicsystems/undr#1]
I tried installing undr so I could download and mess around with reading in AEDAT spike train data.
I get an SSL verify failure. Do you think I can just turn SSL verification off momentarily in code?

Is the problem partially one of credentials? Like the databases I am trying to read from may not be public, and its assumed I am signed in through the shell?
```
~/git/undr$ python3 -m undr install
🦘 provision
(1 / 5) dvs09Traceback (most recent call last):
  File "/home/rudolph/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/rudolph/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/rudolph/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/rudolph/anaconda3/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/home/rudolph/anaconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/rudolph/anaconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/rudolph/anaconda3/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/rudolph/anaconda3/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/rudolph/anaconda3/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rudolph/anaconda3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/rudolph/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/rudolph/anaconda3/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='rds.westernsydney.edu.au', port=443): Max retries exceeded with url: /Institutes/MARCS/ICNS/UNDR/dvs09/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rudolph/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/rudolph/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/rudolph/anaconda3/lib/python3.8/site-packages/undr/__main__.py", line 223, in <module>
    configuration.provision(force=args.force, quiet=False, workers_count=args.workers_count)
  File "/home/rudolph/anaconda3/lib/python3.8/site-packages/undr/__init__.py", line 653, in provision
    dataset.provision(prefix=None if quiet else f"{format_count(index, len(self.datasets))} {name}")
  File "/home/rudolph/anaconda3/lib/python3.8/site-packages/undr/__init__.py", line 311, in provision
    self.server.download(
  File "/home/rudolph/anaconda3/lib/python3.8/site-packages/undr/remote.py", line 395, in download
    workload = self.workload(resources=(resource,), force=force, try_alternatives=try_alternatives, workers_count=1)
  File "/home/rudolph/anaconda3/lib/python3.8/site-packages/undr/remote.py", line 457, in workload
    return super().workload(resources=resources, force=force, try_alternatives=try_alternatives, workers_count=1)
  File "/home/rudolph/anaconda3/lib/python3.8/site-packages/undr/remote.py", line 306, in workload
    worker_target()
  File "/home/rudolph/anaconda3/lib/python3.8/site-packages/undr/remote.py", line 284, in worker_target
    resource, to_download_size, downloaded_size = self.resource_pick_from(
  File "/home/rudolph/anaconda3/lib/python3.8/site-packages/undr/remote.py", line 235, in resource_pick_from
    _, total_size = self.accept_ranges_and_size(session=session, resource=resource)
  File "/home/rudolph/anaconda3/lib/python3.8/site-packages/undr/remote.py", line 440, in accept_ranges_and_size
    response = session.get(parent_url, timeout=self._timeout)
  File "/home/rudolph/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/rudolph/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/rudolph/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/rudolph/anaconda3/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='rds.westernsydney.edu.au', port=443): Max retries exceeded with url: /Institutes/MARCS/ICNS/UNDR/dvs09/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
```

**Comment by aMarcireau** [comment]
Hi Russell,

UNDR is a work-in-progress and I'm working on major changes that may fix this problem. Nevertheless thank you for the report, I'll keep an eye on this issue.
